"""
Script to create PowerPoint presentation for Update Manager project
Requires: pip install python-pptx
"""

from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor

def create_presentation():
    # Create presentation object
    prs = Presentation()
    
    # Set slide dimensions (16:9 aspect ratio)
    prs.slide_width = Inches(10)
    prs.slide_height = Inches(7.5)
    
    # Define colors
    primary_color = RGBColor(0, 51, 102)  # Dark blue
    accent_color = RGBColor(0, 102, 204)  # Blue
    text_color = RGBColor(0, 0, 0)  # Black
    white = RGBColor(255, 255, 255)
    
    # Slide 1: Title Slide
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    title.text = "Update Manager"
    subtitle.text = "Product Release Management System for Accops Products\n\nStreamlining Version Control, Rollout, and Lifecycle Management\n\nAccops Technologies - 2025"
    
    # Slide 2: Agenda
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    title = slide.shapes.title
    title.text = "Agenda"
    content = slide.placeholders[1]
    tf = content.text_frame
    tf.text = "• Overview & Problem Statement"
    p = tf.add_paragraph()
    p.text = "• Solution Architecture"
    p = tf.add_paragraph()
    p.text = "• Key Features & Capabilities"
    p = tf.add_paragraph()
    p.text = "• Supported Products"
    p = tf.add_paragraph()
    p.text = "• Technical Stack"
    p = tf.add_paragraph()
    p.text = "• Implementation Phases"
    p = tf.add_paragraph()
    p.text = "• Benefits & Value Proposition"
    p = tf.add_paragraph()
    p.text = "• Demo & Screenshots"
    p = tf.add_paragraph()
    p.text = "• Future Roadmap"
    
    # Slide 3: Overview
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    title = slide.shapes.title
    title.text = "Overview"
    content = slide.placeholders[1]
    tf = content.text_frame
    tf.text = "What is Update Manager?"
    p = tf.add_paragraph()
    p.text = "\nA comprehensive automated update system and management portal for Accops products that:"
    p = tf.add_paragraph()
    p.text = "• Streamlines version control and rollout of updates"
    p = tf.add_paragraph()
    p.text = "• Provides proactive admin notifications"
    p = tf.add_paragraph()
    p.text = "• Ensures product versions are current, compatible, and centrally managed"
    p = tf.add_paragraph()
    p.text = "• Reduces manual overhead and upgrade errors"
    p = tf.add_paragraph()
    p.text = "\nMission: Enhance operational efficiency and product lifecycle transparency"
    
    # Slide 4: Problem Statement
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    title = slide.shapes.title
    title.text = "Problem Statement"
    content = slide.placeholders[1]
    tf = content.text_frame
    tf.text = "Current Challenges"
    p = tf.add_paragraph()
    p.text = "\n❌ Manual Upgrade Processes"
    p.level = 0
    p = tf.add_paragraph()
    p.text = "   • Time-consuming and error-prone"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Lack of centralized visibility"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "\n❌ Version Management Complexity"
    p.level = 0
    p = tf.add_paragraph()
    p.text = "   • Multiple products across different platforms"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Compatibility tracking difficulties"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "\n❌ Limited Visibility"
    p.level = 0
    p = tf.add_paragraph()
    p.text = "   • No real-time status updates"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Difficult to track deployment versions"
    p.level = 1
    
    # Slide 5: Solution Overview
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    title = slide.shapes.title
    title.text = "Solution Overview"
    content = slide.placeholders[1]
    tf = content.text_frame
    tf.text = "Update Manager - Complete Solution"
    p = tf.add_paragraph()
    p.text = "\n✅ Centralized Portal"
    p.level = 0
    p = tf.add_paragraph()
    p.text = "   • Real-time dashboard with version status"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Visual indicators for pending updates"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Batch update capabilities"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "\n✅ Automated Workflows"
    p.level = 0
    p = tf.add_paragraph()
    p.text = "   • Version detection and notifications"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Compatibility validation"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Release approval workflow"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "\n✅ Customer Management"
    p.level = 0
    p = tf.add_paragraph()
    p.text = "   • Multi-tenant support"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Deployment tracking"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • License management"
    p.level = 1
    
    # Slide 6: Architecture
    slide = prs.slides.add_slide(prs.slide_layouts[5])  # Blank layout
    title_shape = slide.shapes.add_textbox(Inches(0.5), Inches(0.3), Inches(9), Inches(0.8))
    title_frame = title_shape.text_frame
    title_frame.text = "Architecture Overview"
    title_frame.paragraphs[0].font.size = Pt(32)
    title_frame.paragraphs[0].font.bold = True
    
    # Add architecture text
    arch_text = slide.shapes.add_textbox(Inches(0.5), Inches(1.5), Inches(9), Inches(5.5))
    arch_frame = arch_text.text_frame
    arch_frame.text = "Update Manager Portal (React)"
    arch_frame.paragraphs[0].font.size = Pt(18)
    arch_frame.paragraphs[0].font.bold = True
    p = arch_frame.add_paragraph()
    p.text = "  • Dashboard, Release Management, Customer UI"
    p.font.size = Pt(14)
    p = arch_frame.add_paragraph()
    p.text = "\nRESTful API Layer (Go Backend)"
    p.font.size = Pt(18)
    p.font.bold = True
    p = arch_frame.add_paragraph()
    p.text = "  • Product/Version Management"
    p.font.size = Pt(14)
    p = arch_frame.add_paragraph()
    p.text = "  • Customer/Tenant/Deployment APIs"
    p.font.size = Pt(14)
    p = arch_frame.add_paragraph()
    p.text = "  • License Management"
    p.font.size = Pt(14)
    p = arch_frame.add_paragraph()
    p.text = "\nMongoDB Database"
    p.font.size = Pt(18)
    p.font.bold = True
    p = arch_frame.add_paragraph()
    p.text = "  • Products, Versions, Customers"
    p.font.size = Pt(14)
    p = arch_frame.add_paragraph()
    p.text = "  • Deployments, Licenses, Audit Logs"
    p.font.size = Pt(14)
    
    # Slide 7: Key Features - Product Management
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    title = slide.shapes.title
    title.text = "Key Features - Product Management"
    content = slide.placeholders[1]
    tf = content.text_frame
    tf.text = "📦 Product Management"
    p = tf.add_paragraph()
    p.text = "   • Support for all Accops products (Server & Client)"
    p = tf.add_paragraph()
    p.text = "   • Product metadata and categorization"
    p = tf.add_paragraph()
    p.text = "   • Multi-platform support (Windows, Linux, Mobile)"
    p = tf.add_paragraph()
    p.text = "\n🔢 Version Management"
    p = tf.add_paragraph()
    p.text = "   • Semantic versioning support"
    p = tf.add_paragraph()
    p.text = "   • Release types: Security, Feature, Maintenance, Major"
    p = tf.add_paragraph()
    p.text = "   • Version states: Draft → Pending Review → Approved → Released"
    p = tf.add_paragraph()
    p.text = "\n📝 Release Notes"
    p = tf.add_paragraph()
    p.text = "   • Structured release notes format"
    p = tf.add_paragraph()
    p.text = "   • What's New, Bug Fixes, Breaking Changes"
    p = tf.add_paragraph()
    p.text = "   • Compatibility information"
    p = tf.add_paragraph()
    p.text = "   • Upgrade instructions"
    
    # Slide 8: Key Features - Release Workflow
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    title = slide.shapes.title
    title.text = "Key Features - Release Workflow"
    content = slide.placeholders[1]
    tf = content.text_frame
    tf.text = "Streamlined Release Process"
    p = tf.add_paragraph()
    p.text = "\nPre-Release Phase"
    p.level = 0
    p.font.bold = True
    p = tf.add_paragraph()
    p.text = "1. Version preparation with metadata"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "2. Compatibility validation"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "3. Package upload with integrity checks"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "\nRelease Phase"
    p.level = 0
    p.font.bold = True
    p = tf.add_paragraph()
    p.text = "4. Release approval workflow"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "5. Automatic notification generation"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "6. Release notes publication"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "\nPost-Release Phase"
    p.level = 0
    p.font.bold = True
    p = tf.add_paragraph()
    p.text = "7. Update detection"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "8. Update rollout management"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "9. Progress tracking and audit logging"
    p.level = 1
    
    # Slide 9: Customer Management
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    title = slide.shapes.title
    title.text = "Key Features - Customer Management"
    content = slide.placeholders[1]
    tf = content.text_frame
    tf.text = "Customer, Tenant & Deployment Management"
    p = tf.add_paragraph()
    p.text = "\n👥 Customer Management"
    p.level = 0
    p = tf.add_paragraph()
    p.text = "   • Customer registration and profiles"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Organization details and contact information"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Account status tracking"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "\n🏢 Tenant Management"
    p.level = 0
    p = tf.add_paragraph()
    p.text = "   • Multiple tenants per customer"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Independent deployment organization"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Tenant-level statistics and views"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "\n🚀 Deployment Management"
    p.level = 0
    p = tf.add_paragraph()
    p.text = "   • Product deployments per tenant"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • UAT/Production environment distinction"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Version tracking per deployment"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • User count and license information"
    p.level = 1
    
    # Slide 10: Pending Updates
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    title = slide.shapes.title
    title.text = "Key Features - Pending Updates"
    content = slide.placeholders[1]
    tf = content.text_frame
    tf.text = "Intelligent Update Tracking"
    p = tf.add_paragraph()
    p.text = "\n🔍 Automatic Detection"
    p.level = 0
    p = tf.add_paragraph()
    p.text = "   • Real-time calculation of pending updates"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Version gap analysis (patch, minor, major)"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Security update indicators"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "\n📊 Multi-Level Visibility"
    p.level = 0
    p = tf.add_paragraph()
    p.text = "   • Deployment-level pending updates"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Tenant-level aggregation"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Customer-level dashboard"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • System-wide admin view"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "\n🎯 Smart Prioritization"
    p.level = 0
    p = tf.add_paragraph()
    p.text = "   • Critical: Security releases, EOL approaching"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • High: Major updates, Production deployments"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Normal: Minor/patch updates"
    p.level = 1
    
    # Slide 11: License Management
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    title = slide.shapes.title
    title.text = "Key Features - License Management"
    content = slide.placeholders[1]
    tf = content.text_frame
    tf.text = "Comprehensive License System"
    p = tf.add_paragraph()
    p.text = "\n📜 Subscription Management"
    p.level = 0
    p = tf.add_paragraph()
    p.text = "   • Customer subscriptions"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Time-based and perpetual licenses"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Status tracking (Active, Expired, Suspended)"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "\n🎫 License Assignment"
    p.level = 0
    p = tf.add_paragraph()
    p.text = "   • Product-specific licenses"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • User/seat allocation"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • License distribution across tenants/deployments"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "\n📈 License Dashboard"
    p.level = 0
    p = tf.add_paragraph()
    p.text = "   • Utilization tracking"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Expiration warnings (30/60/90 days)"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Compliance reporting"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Allocation history"
    p.level = 1
    
    # Slide 12: Notifications
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    title = slide.shapes.title
    title.text = "Key Features - Notifications"
    content = slide.placeholders[1]
    tf = content.text_frame
    tf.text = "Automated Notification System"
    p = tf.add_paragraph()
    p.text = "\n🔔 Automatic Detection"
    p.level = 0
    p = tf.add_paragraph()
    p.text = "   • New version release detection"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Affected customer identification"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Deployment-level impact analysis"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "\n📧 Multi-Channel Delivery"
    p.level = 0
    p = tf.add_paragraph()
    p.text = "   • In-app notifications with real-time polling"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Notification center with badge counts"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Email notifications (future)"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "\n📋 Smart Notifications"
    p.level = 0
    p = tf.add_paragraph()
    p.text = "   • Priority-based delivery"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • UAT vs Production distinction"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Release notes summary"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Direct action links"
    p.level = 1
    
    # Slide 13: Supported Products
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    title = slide.shapes.title
    title.text = "Supported Products"
    content = slide.placeholders[1]
    tf = content.text_frame
    tf.text = "Accops Product Portfolio"
    p = tf.add_paragraph()
    p.text = "\nServer Products"
    p.level = 0
    p.font.bold = True
    p = tf.add_paragraph()
    p.text = "   • HyWorks - Application virtualization platform"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • HySecure - Secure remote access/VPN"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • IRIS - Identity and access management"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • ARS - Resource management and provisioning"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "\nClient Products"
    p.level = 0
    p.font.bold = True
    p = tf.add_paragraph()
    p.text = "   • Clients for Linux - Linux client applications"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Clients for Windows - Windows client applications"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Mobile Clients - iOS and Android apps"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "\nUpdate Strategies"
    p.level = 0
    p.font.bold = True
    p = tf.add_paragraph()
    p.text = "   • Blue-Green Deployment (Server products - zero downtime)"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • In-Place Updates (Client products)"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • App Store Distribution (Mobile)"
    p.level = 1
    
    # Slide 14: Technical Stack
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    title = slide.shapes.title
    title.text = "Technical Stack"
    content = slide.placeholders[1]
    tf = content.text_frame
    tf.text = "Modern Technology Stack"
    p = tf.add_paragraph()
    p.text = "\nBackend"
    p.level = 0
    p.font.bold = True
    p = tf.add_paragraph()
    p.text = "   • Go 1.21+ - High-performance backend"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • MongoDB 6.0+ - Flexible document database"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • JWT Authentication - Secure API access"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • RESTful API - Standard HTTP endpoints"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "\nFrontend"
    p.level = 0
    p.font.bold = True
    p = tf.add_paragraph()
    p.text = "   • React - Modern UI framework"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • TypeScript - Type-safe development"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Tailwind CSS - Utility-first styling"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Playwright - E2E testing"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "\nInfrastructure"
    p.level = 0
    p.font.bold = True
    p = tf.add_paragraph()
    p.text = "   • Docker - Containerization"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Makefile - Build automation"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Load Testing - Artillery for performance"
    p.level = 1
    
    # Slide 15: Implementation Phases
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    title = slide.shapes.title
    title.text = "Implementation Phases"
    content = slide.placeholders[1]
    tf = content.text_frame
    tf.text = "Phased Delivery Approach"
    p = tf.add_paragraph()
    p.text = "\nPhase 1: Foundation & Core Release Management ✅"
    p.level = 0
    p.font.bold = True
    p = tf.add_paragraph()
    p.text = "   • Product and version management"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Package upload and storage"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Release approval workflow"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Basic portal UI"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "\nPhase 2: Enhanced Release Management ✅"
    p.level = 0
    p.font.bold = True
    p = tf.add_paragraph()
    p.text = "   • Compatibility validation"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Notification system"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Update detection"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Update rollout management"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "\nPhase 3: Integration & Optimization ✅"
    p.level = 0
    p.font.bold = True
    p = tf.add_paragraph()
    p.text = "   • Pending updates integration"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Performance caching"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Enhanced testing"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Workflow automation"
    p.level = 1
    
    # Slide 16: Benefits - Operational Efficiency
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    title = slide.shapes.title
    title.text = "Benefits - Operational Efficiency"
    content = slide.placeholders[1]
    tf = content.text_frame
    tf.text = "Operational Benefits"
    p = tf.add_paragraph()
    p.text = "\n⏱️ Time Savings"
    p.level = 0
    p = tf.add_paragraph()
    p.text = "   • Automated update detection"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Batch update capabilities"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Reduced manual coordination"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "\n👁️ Visibility"
    p.level = 0
    p = tf.add_paragraph()
    p.text = "   • Real-time status dashboard"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Centralized version tracking"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Comprehensive audit trails"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "\n🔄 Automation"
    p.level = 0
    p = tf.add_paragraph()
    p.text = "   • Automated notifications"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Compatibility validation"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Release workflow automation"
    p.level = 1
    
    # Slide 17: Benefits - Risk Reduction
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    title = slide.shapes.title
    title.text = "Benefits - Risk Reduction"
    content = slide.placeholders[1]
    tf = content.text_frame
    tf.text = "Risk Mitigation"
    p = tf.add_paragraph()
    p.text = "\n✅ Compatibility Assurance"
    p.level = 0
    p = tf.add_paragraph()
    p.text = "   • Pre-update compatibility validation"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Upgrade path calculations"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Dependency checking"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "\n🛡️ Security"
    p.level = 0
    p = tf.add_paragraph()
    p.text = "   • Security release prioritization"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Integrity verification (checksums)"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Secure package distribution"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "\n🔄 Rollback Capability"
    p.level = 0
    p = tf.add_paragraph()
    p.text = "   • Update failure handling"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Version rollback support"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Audit trail for compliance"
    p.level = 1
    
    # Slide 18: Benefits - Customer Experience
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    title = slide.shapes.title
    title.text = "Benefits - Customer Experience"
    content = slide.placeholders[1]
    tf = content.text_frame
    tf.text = "Enhanced Customer Experience"
    p = tf.add_paragraph()
    p.text = "\n🎯 Proactive Communication"
    p.level = 0
    p = tf.add_paragraph()
    p.text = "   • Automatic notifications on new releases"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Release notes with clear information"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Upgrade path guidance"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "\n📱 Self-Service Portal"
    p.level = 0
    p = tf.add_paragraph()
    p.text = "   • Customer dashboard"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Deployment management"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Version tracking"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "\n📊 Transparency"
    p.level = 0
    p = tf.add_paragraph()
    p.text = "   • Clear version status"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Pending updates visibility"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • License utilization tracking"
    p.level = 1
    
    # Slide 19: Future Roadmap
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    title = slide.shapes.title
    title.text = "Future Roadmap"
    content = slide.placeholders[1]
    tf = content.text_frame
    tf.text = "Upcoming Enhancements"
    p = tf.add_paragraph()
    p.text = "\nPhase 4: Advanced Features"
    p.level = 0
    p.font.bold = True
    p = tf.add_paragraph()
    p.text = "   • Update Agent implementation"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Automated update scheduling"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • A/B testing capabilities"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Update preview/sandbox"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "\nPhase 5: Integration"
    p.level = 0
    p.font.bold = True
    p = tf.add_paragraph()
    p.text = "   • CI/CD pipeline integration"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Third-party monitoring tools"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Mobile app for management"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Advanced analytics dashboard"
    p.level = 1
    
    # Slide 20: Conclusion
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    title = slide.shapes.title
    title.text = "Conclusion"
    content = slide.placeholders[1]
    tf = content.text_frame
    tf.text = "Update Manager - Transforming Product Release Management"
    p = tf.add_paragraph()
    p.text = "\nKey Takeaways"
    p.level = 0
    p.font.bold = True
    p = tf.add_paragraph()
    p.text = "   • Centralized version control and visibility"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Automated workflows reduce manual overhead"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Enhanced customer experience"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Enterprise-grade security and compliance"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Scalable and performant architecture"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "\nValue Delivered"
    p.level = 0
    p.font.bold = True
    p = tf.add_paragraph()
    p.text = "   • Operational efficiency improvements"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Risk reduction through automation"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Better customer engagement"
    p.level = 1
    p = tf.add_paragraph()
    p.text = "   • Comprehensive audit and compliance"
    p.level = 1
    
    # Slide 21: Thank You
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    title.text = "Thank You!"
    subtitle.text = "Questions & Discussion\n\nProject Repository: UpdateManager\nDocumentation: /docs directory\nAPI Specification: /docs/api-specification.md\n\nAccops Technologies - 2025"
    
    # Save presentation
    prs.save('UpdateManager_Presentation.pptx')
    print("PowerPoint presentation created successfully: UpdateManager_Presentation.pptx")

if __name__ == "__main__":
    create_presentation()

